services:
  - type: background
    name: discord-bot
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node ./build/index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID  
        sync: false
      - key: NODE_ENV
        value: production
